### ISSUE TITLE
safyasi

### ISSUE THREAD

**Issue by ustun** [vigo/devpod#2]
Bazi yerlerde safyasi yaziyor sayfasi yerine Ugur Abi, hangi dosyada bulamadim ama.

**Comment by vigo** [comment]
anlamadım ki? nerede yazıyor? proje içinde "sayfa", "safy" arattım ama bulamadım?

**Comment by ustun** [comment]
hmm sitede degil buradaymis: http://us6.campaign-archive2.com/?u=97dc390c1ceba026d06a28735&id=c1db8e0fa0

**Comment by vigo** [comment]
okay...
